const answers = [
  "72 vírgenes.",
  "8 onzas de heroína colombiana.",
  "Un barril de 50 litros de lubricante.",
  "Un pozo lleno de cunaguaros.",
  "Un arbolito de navidad con ensalada rusa debajo.",
  "Una maldición guajira.",
  "Un pepito frío.",
  "Una presentación de Powerpoint.",
  "Una pistola de agua llena de pipí.",
  "Una bolsa de caraotas mágicas.",
  "Un desayuno balanceado.",
  "A beached whale.",
  "Un güevo e' negro.",
  "Un carajo.",
  "Un güevo más negro y grande.",
  "Un ventiañero usando capucha.",
  "Un ano blanqueado.",
  "Un nini.",
  "Un llorón.",
  "Una circunsición",
  "Un tumor cerebral.",
  "Una parranda de coñazos.",
  "Un video de un gato tan cuchi que te mueres.",
  "Un raspón clandestino en el culo.",
  "Una cava llena de órganos.",
  "Un policía que también es un perro.",
  "Una mano de mierda.",
  "Un rayo láser de la muerte.",
  "Un condón roto.",
  "Una fiesta de cumpleaños decepcionante.",
  "Una cucharada de guasacaca.",
  "Un tiroteo.",
  "Un halcón con capucha.",
  "Un feto.",
  "Una boca sucia.",
  "Un morrocoy hediondo.",
  "Una caricia por dentro del muslo.",
  "A good sniff.",
  "Adolfo Cubas cubierto en aceite de bebé.",
  "Unos maricos jugando volleyball.",
  "Un beta.",
  "Una vida de tristeza.",
  "Bajos estándares de vida.",
  "Una nube de marihuana.",
  "Un tipo en leggins.",
  "Un tipo echando los perros.",
  "Un micropene.",
  "Un viejo en patines.",
  "Un mimo convulsionando.",
  "Un mono fumando Belmont.",
  "El cunaguaro del Pinar que le cortaron las piernas.",
  "Un ajuste de cuentas.",
  "Una ladilla.",
  "Un latinlover.",
  "Una pila de cuerpos.",
  "Una piñata llena de chipos.",
  "Un sombrero depinga.",
  "Una pandilla enemiga.",
  "Un mongólico.",
  "Un dragón triste y gordo sin amigos.",
  "Un pajazo.",
  "Una sorpresa salada",
  "Una negra culona.",
  "Una fiesta de bomberos.",
  "Un mar de peos.",
  "Un universo paralelo ligeramente más mierda.",
  "Un morrocoy mordiéndote la punta del güevo.",
  "Un cover de 'Caballo Viejo'",
  "La Hora Loca en una boda.",
  "Unos carajos con raybans blancos.",
  "Un pelo e' bola.",
  "Un montón de pelo.",
  "Unos pantalones de cuero.",
  "Una nave espacial.",
  "Una explosión nuclear",
  "Un pony.",
  "Una familia disfuncional.",
  "Una cuca que te lleva a otra dimensión.",
  "Un cuello de tortuga incómodo.",
  "Una red de mentiras.",
  "La Lista Tascón.",
  "La papada de Juan Barreto.",
  "Una cachapa.",
  "SIDA.",
  "Desodorante MUM Bolita.",
  "Juan Vicente Gomez.",
  "Pararle bola.",
  "Que te peguen un tiro.",
  "Literalmente robarle un chocolate a un bebé.",
  "La Piedra.",
  "Los Niños de África",
  "Agricultura.",
  "Alcoholismo.",
  "Se te mueren los panas",
  "Gente que se va del país",
  "Toda esta sangre.",
  "Un all-you-can-eat.",
  "Monaguillos.",
  "El Mega Match.",
  "Piedreros.",
  "Un episodio de la Hojilla",
  "Complejo de Edipo",
  "Un colectivo chavista.",
  "Diarrea.",
  "Las tetas de Diosa Canales.",
  "Que se te pare la paloma por horas.",
  "Un rufinol.",
  "Un polichacao honesto sin nada que perder.",
  "Una lobotomía.",
  "Una ola de bachachos.",
  "Collar anal.",
  "Otra película de vampiros mariqueando.",
  "Otro año con Chávez.",
  "Una línea de perico.",
  "Pedir permiso en vez de pedir perdón.",
  "Unas latas en la cola de Mercal.",
  "Arnold Schwarzenegger.",
  "Gochas que no son putas.",
  "Unos cacheteros.",
  "Actitud.",
  "Ramo Verde.",
  "Perros calientes.",
  "Canibalismo.",
  "BATMAN!!!",
  "Bolas.",
  "Henrique Capriles.",
  "Un poco de porfavor.",
  "Pegarle a la jeva.",
  "Cantar la zona.",
  "Harina PAN",
  "Ser un adulto con un poco de diligencias que hacer.",
  "Ser un güevón.",
  "Ser un dinosaurio.",
  "Ser un jodido hechizero.",
  "Ser un buen polvo.",
  "Ser faboloso.",
  "Ser un marginal.",
  "Estar prendido.",
  "Tener real en banda.",
  "Mario Silva revolcándose con cachorritos.",
  "Laureano Marquez hablando paja.",
  "Engrapar la pea.",
  "Perras.",
  "Negros.",
  "Bling bling.",
  "Peos con sopa.",
  "Mamarle el güevo a un bicho en la calle.",
  "Mocos.",
  "Llaneros.",
  "Poner orden en la pea.",
  "Lila Morillo.",
  "Paja.",
  "Ponerte unos pantalones que te quedan bien.",
  "Cards Against Humanity.",
  "Calientagüevos.",
  "Catapultas.",
  "Mal de ojo.",
  "Centauros.",
  "Manos de machetes.",
  "Carisma.",
  "Hacer trampa en las Olimpíadas Especiales.",
  "Abuso de menores.",
  "Candidatas al Miss Venezuela.",
  "Niños con correa.",
  "Caballerosidad.",
  "Edgar Ramírez.",
  "Una linterna.",
  "Muertos del 11 de abril.",
  "Guacucos.",
  "Viejas Cafetalerasß.",
  "Una visita a la morgue de Bello Monte.",
  "Abortos con un gancho de ropa.",
  "Paloma.",
  "Peleas de gallos.",
  "La UCV.",
  "Esconder una carpa.",
  "Consultores.",
  "Hacerse el güevón.",
  "Toser en un papo.",
  "El Gocho de Chicha El Chichero.",
  "Una deuda.",
  "Llorar leyendo Cabrujas.",
  "Oler pega.",
  "Enpiernarse.",
  "Atención al cliente de CANTV.",
  "Mejoras cibernéticas.",
  "Daddy issues.",
  "El cinturón de papi.",
  "Bailar con una escoba.",
  "Darth Vader.",
  "Una violación.",
  "Bebés muertos.",
  "Padres muertos.",
  "Muerto atropellado por Pastor Maldonado.",
  "Desvirgar a una cachifa.",
  "Posesión demoníaca.",
  "Frenillos falsos.",
  "Diosdado.",
  "Dedos de güevo.",
  "Cenar con una muñeco de cartón de Marieta Santana",
  "Changa.",
  "Tirar por el culo.",
  "Hacer lo correcto.",
  "Pizza de Domino's.",
  "Aliento a Dorito.",
  "Double penetración.",
  "Rascarse solo.",
  "Meterse perico para estar despierto",
  "Matar a tiros a un pana.",
  "Respirar muy fuerte",
  "Un enano tosiendo",
  "Morir solo",
  "Morir de diarrea",
  "Morir.",
  "Comerte el bigote de Maduro para obtener superpoderes.",
  "Comerte un cachito de un solo bocado.",
  "Comerte a un bebé.",
  "Comerte un güevo",
  "Comerte el último chigüire que existe.",
  "Papeles desechables.",
  "Japoneses viejos.",
  "Leche de elfo.",
  "Células madres.",
  "Emociones.",
  "Suecas gigantes.",
  "Disfunción eréctil.",
  "Estrógeno.",
  "Genocidio.",
  "Es mejor necesitar un seguro y tenerlo que necesitarlo y no tenerlo.",
  "Lo que esperabas.",
  "Jalarse bola mutuamente",
  "Existir.",
  "Esperar un eructo y echar un waffle en el suelo.",
  "Un niple.",
  "Hacerse las tetas.",
  "Escacez en Mercal.",
  "Una vaina bien.",
  "Tirarse un peo e irse.",
  "El miedo a ser uno mismo.",
  "Darle de comer a Soledad Bravo.",
  "Meterse droga mientras estás preñada.",
  "Unos peos.",
  "Flan piche.",
  "Echarse quesillo en las nalgas.",
  "Conseguir el segundo audio.",
  "Conseguir un esqueleto.",
  "Pintar con los dedos.",
  "Meterle el dedo.",
  "Tiros al aire.",
  "Fisting.",
  "Billetes de 100.",
  "Una vaguada.",
  "Quedarse cagando en bolsa.",
  "La paloma.",
  "Robots voladores que matan gente.",
  "Cuaimas voladoras.",
  "Un prepucio.",
  "Olvidar el 11 de abril.",
  "Chávez.",
  "Vainas gratis.",
  "Fricción.",
  "Plomo al hampa.",
  "Panas que se comen toda mierda.",
  "Amigos con derecho.",
  "Acabar el trapo.",
  "La zona de cruising del cerro Avila.",
  "Spoilear Game of Thrones",
  "Cine tetica.",
  "Gandalf.",
  "Aliens maricos",
  "Pollo.",
  "Super guardias nacionales.",
  "Genghis Khan.",
  "Piercings en la paloma.",
  "La pollina de Carlos Baute.",
  "Porno de estacionamiento de maracay.",
  "Que te secuestre Robert Serra.",
  "Echarte una pea con Listerine.",
  "Que te coja el cast de Improvisto.",
  "Quitarle las pantaletas, elegantemente.",
  "Desnudarse para ver Globovisión.",
  "Meterse droga.",
  "Arrecharte tanto que te cagas un poquito.",
  "Ghandi.",
  "La llorona.",
  "Envolver un hamster en envoplast.",
  "Jevas que se la pasan hablando por Whatsapp.",
  "Dar el 110%.",
  "Juego de barrios.",
  "Calentamiento global.",
  "Gloryholes.",
  "Chocochitas.",
  "Un chivo comiendo una lata.",
  "Orcos.",
  "Dios.",
  "Ir por la vida soltando coñazos.",
  "Lluvia de oro.",
  "No hablar como un tuki.",
  "Abuela.",
  "Las cenizas del abuelo.",
  "Contenido no apto para niños.",
  "Asaltatumbas.",
  "Carajos que no llaman luego de la primera cita.",
  "Calentarla.",
  "Harry Potter erotica.",
  "Tirar sobre una pizza.",
  "Tener chuzos en lugar de piernas.",
  "Huérfanos de padre.",
  "María Isabel de Chávez.",
  "No ser marico.",
  "La mirada asesina de Maria Corina.",
  "Hipsters de la castellana.",
  "Revisionistas históricos.",
  "La Universidad Bolivariana.",
  "El video porno de Diosa Canales.",
  "Lateros.",
  "Esperanza.",
  "Hormonas.",
  "Depilación láser.",
  "Carne de chivo.",
  "Queso caliente..",
  "Gente bella..",
  "Hulk Hogan.",
  "El Desastre de Vargas.",
  "La Inmaculada Concepción.",
  "Música llanera.",
  "Incesto.",
  "Soledad indescriptible.",
  "Lujuría sin límites.",
  "Diseño Inteligente.",
  "Problemas en el cuarto.",
  "Italianos.",
  "Jafar.",
  "Jean-Claude Van Damme.",
  "Jeff Goldblum.",
  "Pajearse en una piscina de lágrimas de carajitos.",
  "Jew-fros.",
  "Una sinagoga.",
  "Hablar paja.",
  "Jose Gregorio Hernandez.",
  "Julio Borges.",
  "Brincarle a la gente.",
  "Solo la puntita miamol.",
  "Justin Bieber.",
  "Morotizados.",
  "Kanye West.",
  "Keanu Reaves.",
  "Un vacío de Polar.",
  "Chamos con cáncer de culo.",
  "Kim-Jong-il.",
  "Un GI Joe en un pesebre.",
  "Lactar.",
  "Lady Gaga.",
  "La bola perdida de Lance Armstrong.",
  "Minas antipersonakes.",
  "Empollar un huevo.",
  "Dejar un mensaje en la contestadora.",
  "Lepra.",
  "Decepcionar a todo el mundo.",
  "Subir de nivel.",
  "Lamer vainas para decir que son tuyas.",
  "Comemierda, literal.",
  "Vivir en la calle.",
  "Loki, el hermano de Thor.",
  "Hablapaja.",
  "Fantasías chavistas.",
  "Quemar las arepas..",
  "Ser una paloma.",
  "Conocer a un pana.",
  "Poner cara de culo.",
  "Besar un güego.",
  "El Sambil.",
  "Carne de hombre.",
  "Pajearte.",
  "Tiempo para uno.",
  "Yo.",
  "MechaHitler.",
  "Cobertura mediatica.",
  "Música en vivo.",
  "Hombres.",
  "La Regla.",
  "Michael Jackson.",
  "Los abdominales de Leopoldo López.",
  "Un poquito de autismo.",
  "Gritar.",
  "Doble morar.",
  "La voz de El CHUUUUUNIOR.",
  "Herpes en la boca.",
  "Marico, voltea.",
  "La escena donde muere Mufasa.",
  "Allahu akbar.",
  "Múltiples puñaladas.",
  "Caerse a tiros.",
  "Mi colección de dildos.",
  "Mi primer muerto.",
  "Mi paloma.",
  "La prima que está buena.",
  "Mis nalgas.",
  "Mis peos internos.",
  "Mi machete.",
  "Mi estado civil.",
  "Mi vida sexual.",
  "Mi alma.",
  "Mi cuca.",
  "Natalie Portman.",
  "Agrandarme la paloma.",
  "Selección natural.",
  "Nazis.",
  "Necrofilia.",
  "Neil Patrick Harris.",
  "Musica del centro piramidal del sambil.",
  "Voz Veis.",
  "Nicolas Cage.",
  "Pezones que cortan.",
  "La Baralt de noche.",
  "No servir pa' un coño.",
  "Que te sepan a mierda los pobres.",
  "No tener sexo.",
  "No devolver un mamerto.",
  "Nada.",
  "Esclavitud moderna.",
  "Bailar merengue en una boda.",
  "Obesidad.",
  "Inamovilidad laboral..",
  "Olor a viejo.",
  "Música de fondo.",
  "Una anillo para gobernarlos a todos.",
  "Mil torontos.",
  "Oompa-Loompas.",
  "Pulgares opuestos.",
  "Sobrecompensar.",
  "Joder a tu papá.",
  "Pegarle a tu madre.",
  "Chupetas gigantes.",
  "Cerveza Polar.",
  "Pac-Man incontrolablemente ahogandose en semen.",
  "Pandas tirando",
  "Pantaletas.",
  "Separar el Mar Rojo.",
  "Aguafiestas..",
  "Trans.",
  "Mear una piedra de riñón.",
  "Post-its pasivo-agresivos.",
  "Pedófilos.",
  "Mear un poquito.",
  "Envidiarle el güevo a un pana.",
  "Cuadrarte culos en una clínica de abortos.",
  "Fotos de tetas.",
  "Darle un cachazo a un rehen.",
  "Bukkake.",
  "Polichacao.",
  "Cagar pa' lante y pa' tras. Por siempre.",
  "Decisiones, cada día. Alguien pierde, alguien ganaß.",
  "Gente pobre.",
  "Chistes ofensivos del Holocausto.",
  "Pornstars.",
  "Muslos robustos.",
  "Bailar.",
  "Soltar las plumas",
  "Carajitos.",
  "Fingir felicidad.",
  "Fingir que te importa.",
  "Jugar truco.",
  "Huevos de pterodáctilo.",
  "Pubertad.",
  "Escarnio público.",
  "Acabar dentro.",
  "Parir cada 9 meses.",
  "¡Cachorritos!",
  "Meter una lonja de queso Paisa en el bluray.",
  "Tirarse un peo con la cuca.",
  "Quiche.",
  "Apretar las nalgas.",
  "Preguntas de CNU.",
  "Racismo.",
  "Violar y saquear.",
  "Re-regalar.",
  "Represión.",
  "Chavistas.",
  "Tirar arrecho.",
  "El vaquero invertido.",
  "Cabalgar por el horizonte.",
  "Arrancarle el corazón a un hombre.",
  "Revolcarte en tu tumba.",
  "Callejero.",
  "Luis Chataing.",
  "RoboCop.",
  "El Conde del Guacharo.",
  "Carlos Andrés Pérez.",
  "Roofies.",
  "Correr desnudo por la calle y cagarse encima.",
  "Chino sin camisa.",
  "Nacho montado encima de Chino.",
  "Samuel L. Jackson.",
  "El niño Jesús.",
  "La bolsa de San Nicolás.",
  "Cilia Flores.",
  "Solo de saxofón.",
  "Despellejar.",
  "Ciencia.",
  "La iglesia de Pare de Sufrir",
  "Gritar como un loco.",
  "Mal de páramo.",
  "Picazón de bolas.",
  "Rascarse una teta.",
  "Sean Connery.",
  "Sean Penn.",
  "Seducción.",
  "Flagelarte.",
  "Odiarse a uno mismo.",
  "Seppuku.",
  "Abdominales.",
  "Una obra de teatro protagonizada por Nelson Bustamante.",
  "Sexting.",
  "Humillación sexual.",
  "Tensión sexual.",
  "Peleas de almohadas.",
  "Siamesas.",
  "Chespirito.",
  "Pemones.",
  "Ugueth Urbina haciendo parrilla.",
  "Compartir inyectadoras.",
  "Callarse la jeta.",
  "Skeletor.",
  "Meterle un coñazo a una vieja racista.",
  "Cámara lenta.",
  "Lechina.",
  "El queso que sale cuando no te lavas el guevo.",
  "Estornudar y tirarse un peo mientras te haces la paja.",
  "Oler gasolina.",
  "Medias de fútbol.",
  "Cagarte encima.",
  "Un güevón con una guitarra en la playa.",
  "Birdman.",
  "Una vaina demasiado jodida.",
  "Sopa demasiado caliente.",
  "Space Jam en VHS.",
  "Brownies puyaos.",
  "Invitado musical, Trino Mora.",
  "Unos cuadritos.",
  "Gastar real.",
  "Una danta.",
  "Combustión espontánea.",
  "¡Carnavales!",
  "Estereotipos validados.",
  "La voz de seductor de Alex Cabrera.",
  "Reír cuando escuchas palabras que terminan en 'ano'.",
  "Peligro.",
  "Someter a un oso y cogértelo.",
  "Diarrea explosiva.",
  "Pensamientos suicidas.",
  "Arcoiris.",
  "Sexo sorpresa.",
  "Emigrar a Barcelona.",
  "El dulce sabor de la venganza.",
  "Llegar al orgasmo.",
  "Pasarse a Movistar.",
  "Escapar.",
  "Guarimbas.",
  "Arrancarle las bolas y los ojos a alguien y luego ponerle las bolas en los ojos.",
  "Dispararle al Santa de Banesco.",
  "Quitarte la franela.",
  "Tetas operadas..",
  "Enseñarle a un robot lo que se sienta ser amado.",
  "Team-building.",
  "Embarazo juvenil.",
  "Porno de barrio.",
  "Torsión testicular.",
  "Ese culo.",
  "El gordo de la clase..",
  "Beber petróleo.",
  "El Big Bang.",
  "La sangre de cristo.",
  "Una lonchera de los Ositos Cariñositos.",
  "Yanomamis.",
  "El baile del perrito.",
  "El general.",
  "Tú sí eres frescolita.",
  "La Fuerza.",
  "Google.",
  "Sancocho.",
  "Banesquín.",
  "Los Cocodrilos de Caracas.",
  "La Biblia.",
  "El chulo.",
  "Los judíos.",
  "El KKK.",
  "Kool-aid piche.",
  "Musipan.",
  "El Rey León.",
  "Los Criollitos.",
  "El Papa.",
  "Los Nachos de Friday's.",
  "La Venida de Cristo.",
  "El Día de la Juventud.",
  "Los Llanos.",
  "Musicales de navidad de Venevisión.",
  "RCTV.",
  "Un anillo de bodas.",
  "La vía más difícil.",
  "Pedir un taxi.",
  "Meladed llegando tarde.",
  "World of Warcraft.",
  "Un pajazo de tu abuelo.",
  "La pálida.",
  "El clítoris.",
  "Las corporaciones.",
  "El día que atacaron los pájaros.",
  "La Guerra Económica.",
  "Toda la Internet.",
  "La estupidez del hombre.",
  "La fruta prohibida.",
  "Los cuatro brazzos de Vishnu.",
  "Los gays.",
  "Una cámara de cristal.",
  "La vida.",
  "Mexicanos echándole bola.",
  "La luz del día.",
  "El corazón de un margariteño.",
  "Hipo.",
  "La agenda gay.",
  "El cuerpo humano.",
  "La muerte del universo.",
  "La mano invisible.",
  "Arepera socialista.",
  "El lechero.",
  "Un parto.",
  "Mezcla de razas.",
  "La humedad de tu boca.",
  "Lo nuevo de Radiohead.",
  "Una placenta.",
  "Tus padres tirando.",
  "Los lisiados.",
  "El Ciudadano, Leopoldo Castillo.",
  "La destrucción sistemática de la calidad de vida del venezolano.",
  "La Trocha.",
  "Los terroristas.",
  "Porno/",
  "Las manos callosas de los niños que cosen tu ropa.",
  "Las minorías.",
  "El significado de la vida.",
  "El metro.",
  "La violación de nuestros derechos humanos.",
  "Así somos los blancos.",
  "Meterle mano.",
  "Tres meses sin tirar.",
  "Pezones pequeños..",
  "Winston Vallenilla.",
  "Lengua.",
  "El papo de Lilian Tintori.",
  "Demasiada gelatina.",
  "Tripear una bola.",
  "Twittear.",
  "Dos enanas cagandose en una cubeta.",
  "Estupidez humana.",
  "Sopa.",
  "Darle un cuchillo a un mono.",
  "Par de coñazos.",
  "Atropellar a alguien.",
  "Cierre Maágico",
  "Viagra.",
  "Cuadrarse un culo en una guarimba.",
  "Vigilantes.",
  "Aplausos.",
  "Vikingos.",
  "Vomitar en medio de una paja.",
  "Esperar al matrimonio.",
  "Despertar en bolas en Petare.",
  "Sexo con marionetas de terciopelo.",
  "Waterboarding.",
  "Armas de destrucción masiva.",
  "Usar un pulpo como pantaleta.",
  "Darle la vuelta a los interiores para usarlos 2 veces.",
  "Pilates.",
  "Cuando te tiras un peo y crees que te cagaste.",
  "Llorar como una puta.",
  "Azotar a un esclavo desobediente.",
  "Sacártelo.",
  "Blancos.",
  "Oligarcas.",
  "Amas de casa.",
  "Don Francisco.",
  "Guiñarle el ojo a la mamá de un pana.",
  "Limpiarle el culo.",
  "Jevas en comerciales de yogurt.",
  "Voto femenino.",
  "Bla bla bla.",
  "Paz mundial.",
  "ESTE CHAVEZ DE MIERDA",
  "Hongo vaginal.",
  "Iron Man"
];


const questions = [
  "A romantic candlelit dinner would be incomplete without _____.",
  "A successful job interview begins with a firm handshake and ends with _____.",
  "After blacking out during New Year's Eve, I was awoken by _____.",
  "After months of debate, the Occupy Wall Street General Assembly could only agree on “More _____!”",
  "After the earthquake, Sean Penn brought _____ to the people of Haiti.",
  "Alternative medicine is now embracing the curative powers of _____.",
  "And I would have gotten away with it, too, if it hadn't been for _____.",
  "Que fue lo que trajiste para muestra y enseña?",
  "Anthropologists have recently discovered a primitive tribe that worships _____.",
  "As part of his contract, Prince won't perform without _____ in his dressing room.",
  "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for _____.",
  "BILLY MAYS HERE FOR _____.",
  "Before I run for president, I must destroy all evidence of my involvement with _____.",
  "But before I kill you, Mr. Bond, I must show you _____.",
  "Call the law offices of Goldstein & Goldstein, because no one should have to tolerate _____ in the workplace.",
  "Charades was ruined for me forever when my mom had to act out _____.",
  "Coming to Broadway this season, _____: The Musical.",
  "Dear Abby, I'm having some trouble with ______ and would like your advice.",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _____.",
  "During high school I never really fit in until I found _____ club.",
  "During his midlife crisis, my dad got really into _____.",
  "Cuando estoy tirando, me gusta pensar en _____.",
  "Every Christmas my uncle gets drunk and tells the story about _____.",
  "Everyone down on the ground! We don't want to hurt anyone. We're just here for _____.",
  "Finally! A service that delivers _____ right to your door.",
  "Having problems with _____? Try _____!",
  "He who controls _____ controls the world.",
  "Hey baby, come back to my place and I'll show you _____.",
  "How am I maintaining my relationship status.",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.",
  "I drink to forget _____.",
  "I got 99 problems but _____ ain't one.",
  "I learned the hard way that you can't cheer up a grieving friend with _____.",
  "I'm not like the rest of you. I'm too rich and busy for _____.",
  "I'm sorry professor, but I couldn't complete my homework because of _____.",
  "In 1,000 years when paper money is but a distant memory, _____ will be our currency.",
  "In L.A. county Jail, word is you can trade 200 cigarettes for _____.",
  "In Michael Jackson's final moments, he thought about _____.",
  "In Rome, there are whisperings that the Vatican has a secret room devoted to _____.",
  "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _____.",
  "In his new self-produced album, Kanye West raps over the sounds of _____.",
  "In his newest and most difficult stunt, David Blaine must escape from _____.",
  "In its new tourism campaign, Detroit proclaims that it has finally eliminated _____.",
  "In the distant future, historians will agree that _____ marked the beginning of America's decline.",
  "In the new Disney Channel Original Movie, Hannah Montana struggles with _____ for the first time.",
  "In the seventh circle of Hell, sinners must endure _____ for all eternity.",
  "Instead of coal, Santa now gives the bad children _____ .",
  "It's a pity that kids these days are all getting involved with _____.",
  "Jesus is _____.",
  "Life for American Indians was forever changed when the White Man introduced them to _____.",
  "Listen, son. If you want to get involved with _____, I won't stop you. Just steer clear of _____.",
  "Little Miss Muffet, Sat on a tuffet, Eating her curds and _____.",
  "Loving you is easy 'cause you're _____.",
  "MTV's new reality show features eight washed-up celebrities living with _____.",
  "Major League Baseball has banned _____ for giving players an unfair advantage.",
  "Maybe she's born with it. Maybe it's _____.",
  "Members of New York's social elite are paying thousands of dollars just to experience _____.",
  "Money can't buy me love, but it can buy me _____.",
  "My country, 'tis of thee, sweet land of _____.",
  "My gym teacher got fired for adding _____ to the obstacle course.",
  "My life is ruled by a vicious cycle of _____ and _____.",
  "My mom freaked out when she looked at my browser history and found _____.com.",
  "My new favorite porn star is Joey “_____” McGee.",
  "Next from J.K. Rowling: Harry Potter and the Chamber of _____.",
  "Next on ESPN2: The World Series of _____.",
  "Next time on Dr. Phil: How to talk to your child about _____.",
  "On the third day of Christmas, my true love game to me: three French hens, two turtle doves, and _____.",
  "Only two things in life are certain: death and _____.",
  "Science will never explain the origin of _____.",
  "Studies show that lab rats navigate mazes 50% faster after being exposed to _____",
  "TSA guidelines now prohibit _____ on airplanes.",
  "The CIA now interrogates enemy agents by repeatedly subjecting them to _____.",
  "The Five Stages of Grief: denial, anger, bargaining, _____, acceptance.",
  "The blind date was going horribly until we discovered our shared interest in _____.",
  "The class field trip was completely ruined by _____.",
  "The healing process began when I joined a support group for victims of _____.",
  "The socialist governments of Scandanavia have declared that access to – is a basic human right.",
  "The votes are in, and the new high school mascot is _____.",
  "This holiday season, Tim Allen must overcome his fear of _____ to save Christmas.",
  "This is the way the world ends This is the way the world ends Not with a bang but with _____.",
  "This is your captain speaking. Fasten your seatbelts and prepare for _____.",
  "This month's Cosmo: 'Spice up your sex life by bringing ______ into the bedroom.'",
  "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only _____ and his wits.",
  "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of _____.",
  "Tonight on 20/20: What you don't know about _____ could kill you.",
  "Turns out that _____-Man was neither the hero we needed nor wanted.",
  "Wake up, America. Christmas is under attack by secular liberals and their _____.",
  "War! What is it good for?",
  "What am I giving up for Lent?",
  "What are my parents hiding from me?",
  "What brought the orgy to a grinding halt?",
  "What did I bring back from Mexico?",
  "What did Vin Diesel eat for dinner?",
  "What did the US airdrop to the children of Afghanistan?",
  "What do old people smell like?",
  "What does Dick Cheney prefer?",
  "What don't you want to find in your Chinese food?",
  "What ended my last relationship?",
  "What gets better with age?",
  "What gives me uncontrollable gas?",
  "What has been making life difficult at the nudist colony?",
  "What helps Obama unwind?",
  "What is Batman's guilty pleasure?",
  "What keeps me warm during the cold, cold winter?",
  "What left this stain on my couch?",
  "What never fails to liven up the party?",
  "White people like _____.",
  "What will I bring back in time to convince people that I am a powerful wizard?",
  "What will always get you laid?",
  "What would grandma find disturbing, yet oddly charming?",
  "What's Teach for America using to inspire inner city students to succeed?",
  "What's a girl's best friend?",
  "What's my anti-drug?",
  "What's my secret power?",
  "What's that smell?",
  "What's that sound?",
  "What's the crustiest?",
  "What's the gift that keeps on giving?",
  "What's the most emo?",
  "What's the new fad diet?",
  "What's the next Happy Meal toy?",
  "What's there a ton of in heaven?",
  "When I am President of the United States, I will create the Department of _____.",
  "When I am a billionaire, I shall erect a 50-foot statue to commemorate _____.",
  "When I pooped, what came out of my butt?",
  "When Pharaoh remained unmoved, Moses called down a Plague of _____.",
  "When all else fails, I can always masturbate to _____.",
  "When the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _____.",
  "Why am I sticky?",
  "Why can't I sleep at night?",
  "Why do I hurt all over?",
  "_____. kid tested mother approved.",
  "_____. Awesome in theory, kind of a mess in practice.",
  "_____. Betcha can't have just one.",
  "_____. High five bro.",
  "_____. It's a trap!",
  "_____. That's how I want to die.",
  "_____: good to the last drop.",
  "_____? There's an app for that."
];

module.exports = {
  questions: questions,
  answers: answers
};
