const answers = [
  "72 vírgenes.",
  "8 onzas de heroína colombiana.",
  "Un barril de 50 litros de lubricante.",
  "Un pozo lleno de cunaguaros.",
  "Un arbolito de navidad con ensalada rusa debajo.",
  "Una maldición guajira.",
  "Un pepito frío.",
  "Una presentación de Powerpoint.",
  "Una pistola de agua llena de pipí.",
  "Una bolsa de caraotas mágicas.",
  "Un desayuno balanceado.",
  "A beached whale.",
  "Un güevo e' negro.",
  "Un carajo.",
  "Un güevo más negro y grande.",
  "Un ventiañero usando capucha.",
  "Un ano blanqueado.",
  "Un nini.",
  "Un llorón.",
  "Una circunsición",
  "Un tumor cerebral.",
  "Una parranda de coñazos.",
  "Un video de un gato tan cuchi que te mueres.",
  "Un raspón clandestino en el culo.",
  "Una cava llena de órganos.",
  "Un policía que también es un perro.",
  "Una mano de mierda.",
  "Un rayo láser de la muerte.",
  "Un condón roto.",
  "Una fiesta de cumpleaños decepcionante.",
  "Una cucharada de guasacaca.",
  "Un tiroteo.",
  "Un halcón con capucha.",
  "Un feto.",
  "Una boca sucia.",
  "Un morrocoy hediondo.",
  "Una caricia por dentro del muslo.",
  "A good sniff.",
  "Adolfo Cubas cubierto en aceite de bebé.",
  "Unos maricos jugando volleyball.",
  "Un beta.",
  "Una vida de tristeza.",
  "Bajos estándares de vida.",
  "Una nube de marihuana.",
  "Un tipo en leggins.",
  "Un tipo echando los perros.",
  "Un micropene.",
  "Un viejo en patines.",
  "Un mimo convulsionando.",
  "Un mono fumando Belmont.",
  "El cunaguaro del Pinar que le cortaron las piernas.",
  "Un ajuste de cuentas.",
  "Una ladilla.",
  "Un latinlover.",
  "Una pila de cuerpos.",
  "Una piñata llena de chipos.",
  "Un sombrero depinga.",
  "Una pandilla enemiga.",
  "Un mongólico.",
  "Un dragón triste y gordo sin amigos.",
  "Un pajazo.",
  "Una sorpresa salada",
  "Una negra culona.",
  "Una fiesta de bomberos.",
  "Un mar de peos.",
  "Un universo paralelo ligeramente más mierda.",
  "Un morrocoy mordiéndote la punta del güevo.",
  "Un cover de 'Caballo Viejo'",
  "La Hora Loca en una boda.",
  "Unos carajos con raybans blancos.",
  "Un pelo e' bola.",
  "Un montón de pelo.",
  "Unos pantalones de cuero.",
  "Una nave espacial.",
  "Una explosión nuclear",
  "Un pony.",
  "Una familia disfuncional.",
  "Una cuca que te lleva a otra dimensión.",
  "Un cuello de tortuga incómodo.",
  "Una red de mentiras.",
  "La Lista Tascón.",
  "La papada de Juan Barreto.",
  "Una cachapa.",
  "SIDA.",
  "Desodorante MUM Bolita.",
  "Juan Vicente Gomez.",
  "Pararle bola.",
  "Que te peguen un tiro.",
  "Literalmente robarle un chocolate a un bebé.",
  "La Piedra.",
  "Los Niños de África",
  "Agricultura.",
  "Alcoholismo.",
  "Se te mueren los panas",
  "Gente que se va del país",
  "Toda esta sangre.",
  "Un all-you-can-eat.",
  "Monaguillos.",
  "El Mega Match.",
  "Piedreros.",
  "Un episodio de la Hojilla",
  "Complejo de Edipo",
  "Un colectivo chavista.",
  "Diarrea.",
  "Las tetas de Diosa Canales.",
  "Que se te pare la paloma por horas.",
  "Un rufinol.",
  "Un polichacao honesto sin nada que perder.",
  "Una lobotomía.",
  "Una ola de bachachos.",
  "Collar anal.",
  "Otra película de vampiros mariqueando.",
  "Otro año con Chávez.",
  "Una línea de perico.",
  "Pedir permiso en vez de pedir perdón.",
  "Unas latas en la cola de Mercal.",
  "Arnold Schwarzenegger.",
  "Gochas que no son putas.",
  "Unos cacheteros.",
  "Actitud.",
  "Ramo Verde.",
  "Perros calientes.",
  "Canibalismo.",
  "BATMAN!!!",
  "Bolas.",
  "Henrique Capriles.",
  "Un poco de porfavor.",
  "Pegarle a la jeva.",
  "Cantar la zona.",
  "Harina PAN",
  "Ser un adulto con un poco de diligencias que hacer.",
  "Ser un güevón.",
  "Ser un dinosaurio.",
  "Ser un jodido hechizero.",
  "Ser un buen polvo.",
  "Ser faboloso.",
  "Ser un marginal.",
  "Estar prendido.",
  "Tener real en banda.",
  "Mario Silva revolcándose con cachorritos.",
  "Laureano Marquez hablando paja.",
  "Engrapar la pea.",
  "Perras.",
  "Negros.",
  "Bling bling.",
  "Peos con sopa.",
  "Mamarle el güevo a un bicho en la calle.",
  "Mocos.",
  "Llaneros.",
  "Poner orden en la pea.",
  "Lila Morillo.",
  "Paja.",
  "Ponerte unos pantalones que te quedan bien.",
  "Cards Against Humanity.",
  "Calientagüevos.",
  "Catapultas.",
  "Mal de ojo.",
  "Centauros.",
  "Manos de machetes.",
  "Carisma.",
  "Hacer trampa en las Olimpíadas Especiales.",
  "Abuso de menores.",
  "Candidatas al Miss Venezuela.",
  "Niños con correa.",
  "Caballerosidad.",
  "Edgar Ramírez.",
  "Una linterna.",
  "Muertos del 11 de abril.",
  "Guacucos.",
  "Viejas Cafetalerasß.",
  "Clearing a bloody path through Walmart with a scimitar.",
  "Coat hanger abortions.",
  "Cock.",
  "Cockfights.",
  "College.",
  "Concealing a boner.",
  "Consultants.",
  "Copping a feel.",
  "Coughing into a vagina.",
  "Count Chocula.",
  "Crippling debt.",
  "Crying into the pages of Sylvia Plath.",
  "Crystal meth.",
  "Cuddling.",
  "Customer service representatives.",
  "Cybernetic enhancements.",
  "Daddy issues.",
  "Daddy's belt.",
  "Dancing with a broom.",
  "Darth Vader.",
  "Date rape.",
  "Dead babies.",
  "Dead parents.",
  "Death by Steven Seagal.",
  "Deflowering the princess.",
  "Demonic possession.",
  "Dental dams.",
  "Dick Cheney.",
  "Dick fingers.",
  "Dining with cardboard cutouts of the cast of “Friends.”",
  "Disco fever.",
  "Doin' it in the butt.",
  "Doing the right thing.",
  "Domino's Oreo Dessert Pizza.",
  "Dorito breath.",
  "Double penetration.",
  "Drinking alone.",
  "Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy.",
  "Dropping a chandelier on your enemies and riding the rope up.",
  "Dry heaving.",
  "Dwarf tossing.",
  "Dying alone and in pain.",
  "Dying of dysentery.",
  "Dying.",
  "Eating Tom Selleck's mustache to gain his powers.",
  "Eating all of the cookies before the AIDS bake-sale.",
  "Eating an albino.",
  "Eating an entire snowman.",
  "Eating the last known Bison.",
  "Edible underpants.",
  "Elderly Japanese men.",
  "Elf cum.",
  "Embryonic stem cells.",
  "Emotions.",
  "Enormous Scandinavian women.",
  "Erectile dysfunction.",
  "Estrogen.",
  "Ethnic cleansing.",
  "Eugenics.",
  "Euphoria by Calvin Klein.",
  "Exactly what you'd expect.",
  "Exchanging pleasantries.",
  "Existing.",
  "Expecting a burp and vomiting on the floor.",
  "Explosions.",
  "Fabricating statistics.",
  "Escacez en Mercal.",
  "Fancy Feast.",
  "Farting and walking away.",
  "Fear itself.",
  "Feeding Rosie O'Donnell.",
  "Fetal alcohol syndrome.",
  "Fiery poops.",
  "Figgy pudding.",
  "Filling every orifice with butterscotch pudding.",
  "Finding Waldo.",
  "Finding a skeleton.",
  "Finger painting.",
  "Fingering.",
  "Firing a rifle into the air while balls deep in a squealing hog.",
  "Fisting.",
  "Five-Dollar Footlongs.",
  "Flash flooding.",
  "Flesh-eating bacteria.",
  "Flightless birds.",
  "Flying robots that kill people.",
  "Flying sex snakes.",
  "Un prepucio.",
  "Forgetting the Alamo.",
  "Former President George W. Bush.",
  "Free samples.",
  "Friction.",
  "Friendly fire.",
  "Friends who eat all the snacks.",
  "Friends with benefits.",
  "Frolicking.",
  "La zona de cruising del cerro Avila.",
  "Fucking up “Silent Night” in front of 300 parents.",
  "Full frontal nudity.",
  "Gandalf.",
  "Gay aliens",
  "Geese.",
  "Genetically engineered super-soldiers.",
  "Genghis Khan.",
  "Genital piercings.",
  "George Clooney's musk.",
  "Porno de estacionamiento de maracay.",
  "Getting abducted by Peter Pan.",
  "Getting drunk on mouthwash.",
  "Getting hilariously gang-banged by the Blue Man Group.",
  "Getting in her pants, politely.",
  "Getting naked and watching Nickelodeon.",
  "Getting really high.",
  "Getting so angry that you pop a boner.",
  "Getting your dick stuck in a Chinese finger trap with another dick.",
  "Ghandi.",
  "La llorona.",
  "Gift-wrapping a live hamster.",
  "Girls that always be textin'.",
  "Giving 110%.",
  "Gladitorial combat.",
  "Glenn Beck being harried by a swarm of buzzards.",
  "Glenn Beck catching his scrotum on a curtain hook.",
  "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.",
  "Global warming.",
  "Gloryholes.",
  "GoGurt.",
  "Goats eating cans.",
  "Goblins.",
  "God.",
  "Going around punching people.",
  "Golden showers.",
  "No hablar como un tuki.",
  "Grandma.",
  "Grandpa's ashes.",
  "Graphic violence, adult language and some sexual content.",
  "Grave robbing.",
  "Guys who don't call.",
  "Half-assed foreplay.",
  "Harry Potter erotica.",
  "Having sex on top of a pizza.",
  "Having shotguns for legs.",
  "Heartwarming orphans.",
  "Her Royal Highness, Queen Elizabeth II.",
  "Heteronormativity.",
  "La mirada asesina de Maria Corina.",
  "Hipsters de la castellana.",
  "Historical revisionism.",
  "Historically black colleges.",
  "El video porno de Diosa Canales.",
  "Homeless people.",
  "Hope.",
  "Hormone injections.",
  "Horrifying laser hair removal accidents.",
  "Horse meat.",
  "Hot Cheese.",
  "Hot Pockets.",
  "Hot people.",
  "Hulk Hogan.",
  "Hurricane Katrina.",
  "Immaculate conception.",
  "Inappropriate yodeling.",
  "Incest.",
  "Indescribable loneliness.",
  "Insatiable bloodlust.",
  "Intelligent design.",
  "Intimacy problems.",
  "Italians.",
  "Jafar.",
  "Jean-Claude Van Damme.",
  "Jeff Goldblum.",
  "Jerking off into a pool of children's tears.",
  "Jew-fros.",
  "Jewish fraternities.",
  "Jibber-jabber.",
  "Jose Gregorio Hernandez.",
  "Judge Judy.",
  "Jumping out at people.",
  ""Solo la puntita miamol".",
  "Justin Bieber.",
  "Kamikaze pilots.",
  "Kanye West.",
  "Keanu Reaves.",
  "Keg stands.",
  "Kids with ass cancer.",
  "Kim-Jong-il.",
  "Krampus, the Austrian Christmas Monster.",
  "Lactation.",
  "Lady Gaga.",
  "Lance Armstrong's missing testicle.",
  "Land mines.",
  "Laying an egg.",
  "Leaving an awkward voicemail.",
  "Leprosy.",
  "Letting everyone down.",
  "Leveling up.",
  "Licking things to claim them as your own.",
  "Comemierda, literal.",
  "Living in a trashcan.",
  "Lockjaw.",
  "Loki, the trickster god.",
  "Loose lips.",
  "Lumberjack fantasies.",
  "Lunchables.",
  "Mad hacky-sack skills.",
  "Making a friend.",
  "Making a pouty face.",
  "Making the penises kiss.",
  "Making the penises kiss.",
  "Mall Santa.",
  "Man meat.",
  "Pajearte.",
  "Me time.",
  "Me.",
  "MechaHitler.",
  "Media coverage.",
  "Medieval Times Dinner & Tournament.",
  "Men.",
  "La Regla.",
  "Michael Jackson.",
  "Michelle Obama's arms.",
  "Un poquito de autismo.",
  "Mooing.",
  "Moral ambiguity.",
  "La voz de "El CHUUUUUNIOR".",
  "Mouth herpes.",
  "Mr. Clean, right behind you.",
  "La escena donde muere Mufasa.",
  "Muhammad (Praise Be Unto Him).",
  "Multiple stab wounds.",
  "Mutually-assured destruction.",
  "My collection of high-tech sex toys.",
  "My first kill.",
  "My genitals.",
  "My hot cousin.",
  "My humps.",
  "My inner demons.",
  "Mi machete.",
  "My manservant, Claude.",
  "My relationship status.",
  "Mi vida sexual.",
  "My soul.",
  "My vagina.",
  "Natalie Portman.",
  "Natural male enhancement.",
  "Natural selection.",
  "Nazis.",
  "Necrophilia.",
  "Neil Patrick Harris.",
  "Musica del centro piramidal del sambil.",
  "Voz Veis.",
  "Nicolas Cage.",
  "Nipple blades.",
  "Nocturnal emissions.",
  "Not contributing to society in any meaningful way.",
  "Not giving a shit about the Third World.",
  "Not having sex.",
  "Not reciprocating oral sex.",
  "Nothing.",
  "Nublile slave boys.",
  "Nunchuck moves.",
  "Obesity.",
  "Object permanence.",
  "Old-people smell.",
  "Ominous background music.",
  "One Ring to rule them all.",
  "One thousand Slim Jims.",
  "Oompa-Loompas.",
  "Opposable thumbs.",
  "Overcompensation.",
  "Overpowering your father.",
  "Oversized lollipops.",
  "Cerveza Polar.",
  "Pac-Man incontrolablemente ahogandose en semen.",
  "Panda sex.",
  "Panty raids.",
  "Parting the Red Sea.",
  "Party poopers.",
  "Passable transvestites.",
  "Passing a kidney stone.",
  "Passive-aggressive Post-it notes.",
  "Pedophiles.",
  "Peeing a little bit.",
  "Penis envy.",
  "Picking up girls at the abortion clinic.",
  "Pictures of boobs.",
  "Pistol-whipping a hostage.",
  "Pixelated bukkake.",
  "Polichacao.",
  "Pooping back and forth. Forever.",
  "Poor life choices.",
  "Poor people.",
  "Chistes ofensivos del Holocausto.",
  "Porn stars.",
  "Powerful thighs.",
  "Prancing.",
  "Praying the gay away.",
  "Preteens.",
  "Pretending to be happy.",
  "Pretending to care.",
  "Pretty Pretty Princess Dress-Up Board Game.",
  "Pterodactyl eggs.",
  "Pubertad.",
  "Public ridicule.",
  "Pulling out",
  "Pumping out a baby every nine months.",
  "Puppies!",
  "Putting an entire peanut butter and jelly sandwich into the VCR.",
  "Tirarse un peo con la cuca.",
  "Quiche.",
  "Quivering jowls.",
  "Racially-biased SAT questions.",
  "Racism.",
  "Raping and pillaging.",
  "Re-gifting.",
  "Repression.",
  "Chavistas.",
  "Revenge fucking.",
  "Reverse cowgirl.",
  "Riding off into the sunset.",
  "Ripping into a man's chest and pulling out his still-beating heart.",
  "Rising from the grave.",
  "Road head.",
  "Luis Chataing.",
  "RoboCop.",
  "Roland the Farter, flatulist to the king.",
  "Ronald Reagan.",
  "Roofies.",
  "Running naked through a mall, pissing and shitting everywhere.",
  "Ryan Gosling riding in on a white horse.",
  "Same-sex ice dancing.",
  "Samuel L. Jackson.",
  "El niño Jesús.",
  "La bolsa de San Nicolás.",
  "Sarah Palin.",
  "Saxophone solos.",
  "Scalping.",
  "Science.",
  "La iglesia de Pare de Sufrir",
  "Screaming like a maniac.",
  "Scrotal frostbite.",
  "Scrotum tickling.",
  "Scrubbing under the folds.",
  "Sean Connery.",
  "Sean Penn.",
  "Seduction.",
  "Self-flagellation.",
  "Self-loathing.",
  "Seppuku.",
  "Serfdom.",
  "Several intertwining love stories featuring Hugh Grant.",
  "Sexting.",
  "Sexual humiliation.",
  "Sexual tension.",
  "Sexy pillow fights.",
  "Sexy siamese twins.",
  "Shaft.",
  "Shapeshifters.",
  "Shaquille O'Neal's acting career.",
  "Sharing needles.",
  "Shutting the fuck up.",
  "Skeletor.",
  "Meterle un coñazo a una vieja racista.",
  "Slow motion.",
  "Smallpox blankets.",
  "El "queso" que sale cuando no te lavas el guevo.",
  "Sneezing, farting, and coming at the same time.",
  "Sniffing glue.",
  "Socks.",
  "Soiling oneself.",
  "Some douche with an acoustic guitar.",
  "Some kind of bird-man.",
  "Some really fucked-up shit.",
  "Soup that is too hot.",
  "Space Jam on VHS.",
  "Space muffins.",
  "Special musical guest, Cher.",
  "Spectacular abs.",
  "Spending lots of money.",
  "Sperm whales.",
  "Spontaneous human combustion.",
  "Spring break!",
  "Statistically validated stereotypes.",
  "Stephen Hawking talking dirty.",
  "Stifling a giggle at the mention of Hutus and Tutsis.",
  "Stranger danger.",
  "Subduing a grizzly bear and making her your wife.",
  "Sudden Poop Explosion Disease.",
  "Suicidal thoughts.",
  "Sunshine and rainbows.",
  "Surprise sex!",
  "Survivor's guilt.",
  "Sweet, sweet vengeance.",
  "Swiftly achieving orgasm.",
  "Switching to Geico.",
  "Swooping.",
  "Take-backsies.",
  "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.",
  "Taking down Santa with a surface-to-air missiles.",
  "Taking off your shirt.",
  "Tangled Slinkys.",
  "Tasteful sideboob.",
  "Teaching a robot to love.",
  "Team-building exercises.",
  "Teenage pregnancy.",
  "Tentacle porn.",
  "Testicular torsion.",
  "That ass.",
  "That thing that electrocutes your abs.",
  "The American Dream.",
  "El Big Bang.",
  "La sangre de cristo.",
  "The Care Bear Stare.",
  "The Chinese gymnastics team.",
  "The Dance of the Sugar Plum Fairy.",
  "The Donald Trump Seal of Approval.",
  "The Fanta girls.",
  "La Fuerza.",
  "Google.",
  "The Gulags.",
  "The Hamburglar.",
  "The Harlem Globetrotters.",
  "The Holy Bible.",
  "The Hustle.",
  "The Jews.",
  "The KKK.",
  "The Kool-Aid Man.",
  "The Land of Chocolate.",
  "The Little Engine That Could.",
  "The Make-A-Wish foundation.",
  "The Pope.",
  "The Qeusadilla Explosion Salad from Chili's.",
  "The Rapture.",
  "The Rev. Dr. Martin Luther King, Jr.",
  "The South.",
  "The Star Wars Holiday Special.",
  "The Tempur-Pedic Swedish Sleep System.",
  "The Three-Fifths Compromise.",
  "The Trail of Tears.",
  "The Ubermensch.",
  "The Virginia Tech Massacre.",
  "The World of Warcraft.",
  "The boners of the elderly.",
  "The chronic.",
  "The clitoris.",
  "The corporations.",
  "The day the birds attacked.",
  "The economy.",
  "The entire Internet.",
  "The folly of man.",
  "The forbidden fruit.",
  "The four arms of Vishnu.",
  "The gays.",
  "The glass ceiling.",
  "The grey nutrient broth that sustains Mitt Romney.",
  "The hardworking Mexican.",
  "The harsh light of day.",
  "The heart of a child.",
  "The hiccups.",
  "The homosexual agenda.",
  "The human body.",
  "The inevitable heat death of the universe.",
  "The invisible hand.",
  "The mere concept of Applebee's.",
  "The milk man.",
  "The miracle of childbirth.",
  "The mixing of the races.",
  "The moist, demanding chasm of his mouth.",
  "The new Radiohead album.",
  "The placenta.",
  "The primal, ball-slapping sex your parents are having right now.",
  "The profoundly handicapped.",
  "The shambling corpse of Larry King.",
  "The systematic destruction of an entire people and their way of life.",
  "The taint; the grundle; the fleshy fun-bridge.",
  "The terrorists.",
  "The thin veneer of sitautional causality that underlies porn.",
  "The tiny calloused hands of the Chinese  children that made this card.",
  "The token minority.",
  "The true meaning of Christmas.",
  "The underground railroad.",
  "The violation of our most basic human rights.",
  "The way white people is.",
  "Third base.",
  "Three months in the hole.",
  "Tiny nipples.",
  "Winston Vallenilla.",
  "Tongue.",
  "Toni Morrison's vagina.",
  "Too much hair gel.",
  "Tripear una bola.",
  "Tweeting.",
  "Dos enanas cagandose en una cubeta.",
  "Unfathomable stupidity.",
  "Unlimited soup, salad, and breadsticks.",
  "Upgrading homeless people to mobile hotspots.",
  "Uppercuts.",
  "Vehicular manslaughter.",
  "Cierre Maágico",
  "Viagra.",
  "Vietnam flashbacks.",
  "Vigilante justice.",
  "Vigorous jazz hands.",
  "Vikings.",
  "Vomiting mid-blowjob.",
  "Waiting 'til marriage.",
  "Waking up half-naked in a Denny's parking lot.",
  "Warm, velvety muppet sex",
  "Waterboarding.",
  "Weapons-grade plutonium.",
  "Wearing an octopus for a hat.",
  "Wearing underwear inside-out to avoid doing laundry.",
  "Whatever Kwanzaa is supposed to be about.",
  "When you fart and a little bit comes out.",
  "Whining like a little bitch.",
  "Whipping a disobedient slave.",
  "Whipping it out.",
  "White people.",
  "White privilege.",
  "Wifely duties.",
  "William Shatner.",
  "Winking at old people.",
  "Wiping her butt.",
  "Women in yogurt commercials.",
  "Women's suffrage.",
  "Words, words, words.",
  "World peace.",
  "YOU MUST CONSTRUCT ADDITIONAL PYLONS.",
  "Yeast.",
  "Zeus's sexual appetites.",
];


const questions = [
  "A romantic candlelit dinner would be incomplete without _____.",
  "A successful job interview begins with a firm handshake and ends with _____.",
  "After blacking out during New Year's Eve, I was awoken by _____.",
  "After months of debate, the Occupy Wall Street General Assembly could only agree on “More _____!”",
  "After the earthquake, Sean Penn brought _____ to the people of Haiti.",
  "Alternative medicine is now embracing the curative powers of _____.",
  "And I would have gotten away with it, too, if it hadn't been for _____.",
  "Que fue lo que trajiste para "muestra y ensenñ"?",
  "Anthropologists have recently discovered a primitive tribe that worships _____.",
  "As part of his contract, Prince won't perform without _____ in his dressing room.",
  "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for _____.",
  "BILLY MAYS HERE FOR _____.",
  "Before I run for president, I must destroy all evidence of my involvement with _____.",
  "But before I kill you, Mr. Bond, I must show you _____.",
  "Call the law offices of Goldstein & Goldstein, because no one should have to tolerate _____ in the workplace.",
  "Charades was ruined for me forever when my mom had to act out _____.",
  "Coming to Broadway this season, _____: The Musical.",
  "Dear Abby, I'm having some trouble with ______ and would like your advice.",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _____.",
  "During high school I never really fit in until I found _____ club.",
  "During his midlife crisis, my dad got really into _____.",
  "Cuando estoy tirando, me gusta pensar en _____.",
  "Every Christmas my uncle gets drunk and tells the story about _____.",
  "Everyone down on the ground! We don't want to hurt anyone. We're just here for _____.",
  "Finally! A service that delivers _____ right to your door.",
  "Having problems with _____? Try _____!",
  "He who controls _____ controls the world.",
  "Hey baby, come back to my place and I'll show you _____.",
  "How am I maintaining my relationship status.",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.",
  "I drink to forget _____.",
  "I got 99 problems but _____ ain't one.",
  "I learned the hard way that you can't cheer up a grieving friend with _____.",
  "I'm not like the rest of you. I'm too rich and busy for _____.",
  "I'm sorry professor, but I couldn't complete my homework because of _____.",
  "In 1,000 years when paper money is but a distant memory, _____ will be our currency.",
  "In L.A. county Jail, word is you can trade 200 cigarettes for _____.",
  "In Michael Jackson's final moments, he thought about _____.",
  "In Rome, there are whisperings that the Vatican has a secret room devoted to _____.",
  "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _____.",
  "In his new self-produced album, Kanye West raps over the sounds of _____.",
  "In his newest and most difficult stunt, David Blaine must escape from _____.",
  "In its new tourism campaign, Detroit proclaims that it has finally eliminated _____.",
  "In the distant future, historians will agree that _____ marked the beginning of America's decline.",
  "In the new Disney Channel Original Movie, Hannah Montana struggles with _____ for the first time.",
  "In the seventh circle of Hell, sinners must endure _____ for all eternity.",
  "Instead of coal, Santa now gives the bad children _____ .",
  "It's a pity that kids these days are all getting involved with _____.",
  "Jesus is _____.",
  "Life for American Indians was forever changed when the White Man introduced them to _____.",
  "Listen, son. If you want to get involved with _____, I won't stop you. Just steer clear of _____.",
  "Little Miss Muffet, Sat on a tuffet, Eating her curds and _____.",
  "Loving you is easy 'cause you're _____.",
  "MTV's new reality show features eight washed-up celebrities living with _____.",
  "Major League Baseball has banned _____ for giving players an unfair advantage.",
  "Maybe she's born with it. Maybe it's _____.",
  "Members of New York's social elite are paying thousands of dollars just to experience _____.",
  "Money can't buy me love, but it can buy me _____.",
  "My country, 'tis of thee, sweet land of _____.",
  "My gym teacher got fired for adding _____ to the obstacle course.",
  "My life is ruled by a vicious cycle of _____ and _____.",
  "My mom freaked out when she looked at my browser history and found _____.com.",
  "My new favorite porn star is Joey “_____” McGee.",
  "Next from J.K. Rowling: Harry Potter and the Chamber of _____.",
  "Next on ESPN2: The World Series of _____.",
  "Next time on Dr. Phil: How to talk to your child about _____.",
  "On the third day of Christmas, my true love game to me: three French hens, two turtle doves, and _____.",
  "Only two things in life are certain: death and _____.",
  "Science will never explain the origin of _____.",
  "Studies show that lab rats navigate mazes 50% faster after being exposed to _____",
  "TSA guidelines now prohibit _____ on airplanes.",
  "The CIA now interrogates enemy agents by repeatedly subjecting them to _____.",
  "The Five Stages of Grief: denial, anger, bargaining, _____, acceptance.",
  "The blind date was going horribly until we discovered our shared interest in _____.",
  "The class field trip was completely ruined by _____.",
  "The healing process began when I joined a support group for victims of _____.",
  "The socialist governments of Scandanavia have declared that access to – is a basic human right.",
  "The votes are in, and the new high school mascot is _____.",
  "This holiday season, Tim Allen must overcome his fear of _____ to save Christmas.",
  "This is the way the world ends This is the way the world ends Not with a bang but with _____.",
  "This is your captain speaking. Fasten your seatbelts and prepare for _____.",
  "This month's Cosmo: 'Spice up your sex life by bringing ______ into the bedroom.'",
  "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only _____ and his wits.",
  "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of _____.",
  "Tonight on 20/20: What you don't know about _____ could kill you.",
  "Turns out that _____-Man was neither the hero we needed nor wanted.",
  "Wake up, America. Christmas is under attack by secular liberals and their _____.",
  "War! What is it good for?",
  "What am I giving up for Lent?",
  "What are my parents hiding from me?",
  "What brought the orgy to a grinding halt?",
  "What did I bring back from Mexico?",
  "What did Vin Diesel eat for dinner?",
  "What did the US airdrop to the children of Afghanistan?",
  "What do old people smell like?",
  "What does Dick Cheney prefer?",
  "What don't you want to find in your Chinese food?",
  "What ended my last relationship?",
  "What gets better with age?",
  "What gives me uncontrollable gas?",
  "What has been making life difficult at the nudist colony?",
  "What helps Obama unwind?",
  "What is Batman's guilty pleasure?",
  "What keeps me warm during the cold, cold winter?",
  "What left this stain on my couch?",
  "What never fails to liven up the party?",
  "White people like _____.",
  "What will I bring back in time to convince people that I am a powerful wizard?",
  "What will always get you laid?",
  "What would grandma find disturbing, yet oddly charming?",
  "What's Teach for America using to inspire inner city students to succeed?",
  "What's a girl's best friend?",
  "What's my anti-drug?",
  "What's my secret power?",
  "What's that smell?",
  "What's that sound?",
  "What's the crustiest?",
  "What's the gift that keeps on giving?",
  "What's the most emo?",
  "What's the new fad diet?",
  "What's the next Happy Meal toy?",
  "What's there a ton of in heaven?",
  "When I am President of the United States, I will create the Department of _____.",
  "When I am a billionaire, I shall erect a 50-foot statue to commemorate _____.",
  "When I pooped, what came out of my butt?",
  "When Pharaoh remained unmoved, Moses called down a Plague of _____.",
  "When all else fails, I can always masturbate to _____.",
  "When the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _____.",
  "Why am I sticky?",
  "Why can't I sleep at night?",
  "Why do I hurt all over?",
  "_____. kid tested mother approved.",
  "_____. Awesome in theory, kind of a mess in practice.",
  "_____. Betcha can't have just one.",
  "_____. High five bro.",
  "_____. It's a trap!",
  "_____. That's how I want to die.",
  "_____: good to the last drop.",
  "_____? There's an app for that.",
];

module.exports = { questions: questions, answers: answers };
